### ISSUE TITLE
number of online processors when some cores are isolated via kernel

### ISSUE THREAD

**Issue by tjanas** [madler/pigz#100]
On some of my Red Hat Linux machines, I have almost of the online cores isolated via kernel boot parameters (via isolcpus) so that they are unavailable to the OS. However, the mechanism used in [pigz.c](https://github.com/madler/pigz/blob/master/pigz.c) does not account for this, so it spawns far more threads than cores that are truly available.

Example, on one of my 36-core machines:
`/boot/grub/grub.conf` kernel boot parameter 'isolcpus' has 29 cores isolated
`sysconf(_SC_NPROCESSORS_ONLN)` returns 36
`numactl --show` includes a list of cores that are not isolated by the kernel (a total of 7 for this example)

Is there a way for pigz to handle this situation, where it would detect 7 online cores instead of 36 for the above machine?

**Comment by madler** [comment]
You can specify the number of threads using `-p`, so perhaps you can use the output of `numactl` to deduce the number of available cores and feed that to the command line option.

However I wonder what difference it makes. There is likely not much penalty in specifying more cores than you have, other than using more memory for the buffers in all the threads. You should test to see the difference between `-p 7` and `-p 32`, or `-p 100` for that matter. In fact, pigz invokes two more threads than requested (expect when using `-p 1`), one being the main thread and one being a thread to write the output. The _n_ cores in `-p n` is the number of cores for compression.

Of course, if you want the best performance, you don't want to specify fewer cores than you have, so the number of actual cores should always be safe.

**Comment by MichaelReitsma** [comment]
Not being a unix expert in anyway i was wondering why it would be necessary, apart from this example, to specify the number of processors/cores it uses ? Doesn't unix have a multi-core load balancer or something ?
Or is it best to have one core free for other tasks ? 
So if i have a 8 core system and pigz uses 2 cores for other purposes then i should specify a maximum of 5 with -p5?

Edit:
After some more testing i found the processing time to be different between -p8 and -p6 (or even -p7) on a 8 core system. This suggests that specifying 6 or 8 cores is not the same in terms of load. 6 cores should be the same snce pigz claimes an additional 2 for administration overhead.

**Comment by madler** [comment]
@MichaelReitsma You don't need to specify the number of cores. By default pigz will set up twice as many compression threads as there are cores. This is done to have a high probability of keeping all of the cores busy. Other processes on the system will continue to get their fair share of time on the cores. Though their fair share will be less while pigz is trying to keep all the cores busy.

If you have a need to assure that there are some number of cores that pigz will not monopolize (not sure what that need would be), then I would use the number given to `-p` — not that number plus two. The other two threads are to take advantage of parallel input/output operations, not computation, so those two threads will not monopolize cores.
