### ISSUE TITLE
pigz decompress performance drops when overwriting file

### ISSUE THREAD

**Issue by yukha-dw** [madler/pigz#101]
Hello, i have found interesting behaviour when using pigz. When pigz tries to overwrite file, it needs 500% more time to replace the file (or other operations, i'm not quite sure).

top is overwrite.
![image](https://user-images.githubusercontent.com/91457362/163755906-b45c1753-32fb-47ba-bbc7-f49d06b52a3d.png)

I also tried it on gzip, but it has no this interesting behaviour as intended.

**Comment by tansy** [comment]
I noticed that as well but didn't observe such a big difference. In my case it was about 1 second more when overwriting file with `-f`.
It's not consistent either - sometimes it was not a case sometimes, more often than not, it was.

**Comment by madler** [comment]
I can't duplicate this:

```
% cp enwik8.gz xx.gz;cp enwik8.gz yy.gz;pigz -dkf xx.gz;time pigz -df xx.gz;time pigz -df yy.gz
pigz -df xx.gz  0.30s user 0.04s system 113% cpu 0.302 total
pigz -df yy.gz  0.30s user 0.04s system 113% cpu 0.304 total
```

Closing.
