### ISSUE TITLE
Indeterministic results

### ISSUE THREAD

**Issue by haampie** [madler/pigz#104]
Tested with pigz 2.4 and 2.7, I'm running into nondeterminism:
```
$ echo 'x' | pigz -p1 -c > a
$ echo 'x' | pigz -p1 -c > b

$ cmp a b
a b differ: byte 5, line 1

$ hexdump a
0000000 8b1f 0008 1b7e 627d 0300 e0ab 0002 081f
0000010 46ea 0002 0000                         
0000016

$ hexdump b
0000000 8b1f 0008 1b7f 627d 0300 e0ab 0002 081f
0000010 46ea 0002 0000                         
0000016
```

**Comment by haampie** [comment]
Ugh, gzip uses a timestamp in its header. Sorry for the noise.

> a 10-byte header, containing a [magic number](https://en.wikipedia.org/wiki/Magic_number_(programming)) (1f 8b), the compression method (08 for DEFLATE), 1-byte of header flags, a 4-byte timestamp, compression flags and the operating system ID.

**Comment by dirtyharrycallahan** [comment]
If you know the structure you can manipulate it. See strip-nondeterminism
