### ISSUE TITLE
Zipping a directory issue.

### ISSUE THREAD

**Issue by KupQ** [madler/pigz#108]
Hello, 
using following command.
tar -cv -I 'pigz --zip' -f output.tar.zip Directory/ 

it create "output.tar.zip" but the issue it create a file name " - " and store all directory there... is there possible way to create .tar.zip or .zip with Directory inside it? 

pigz is indeed one of the best compression tool specially if you own a powerful sever with multiple cores. 
kindly guide me if there is a way. thank you.

**Comment by madler** [comment]
The `-I` option in both GNU tar and BSD tar reads file names to compress from the give file. What tar are you using?

For GNU tar, you would use the `--use-compress-program` option. I am not finding a similar option for BSD tar, though for any tar you could just pipe the output to the compressor:

```
    tar cv - Directory/ | pigz --zip > output.tar.zip
```

Yes, if you pipe input to `pigz --zip`, it will create a zip file with a single entry with the name `-` containing all of that input compressed. If you were expecting that combining tar and pigz would somehow create a zip file with multiple entries, then no, that won't work. tar and zip are entirely different and unrelated formats.

**Comment by KupQ** [comment]
> The `-I` option in both GNU tar and BSD tar reads file names to archive from the given file. What tar are you using?
> 
> For GNU tar, you would use the `--use-compress-program` option. I am not finding a similar option for BSD tar, though for any tar you could just pipe the output to the compressor:
> 
> ```
>     tar cv - Directory/ | pigz --zip > output.tar.zip
> ```
> 
> Yes, if you pipe input to `pigz --zip`, it will create a zip file with a single entry with the name `-` containing all of that input compressed. If you were expecting that combining tar and pigz would somehow magically create a zip file with multiple entries, then no, that won't work. tar and zip are entirely different and unrelated formats.

Mr.Adler 
Thank you for the answer, 
" If you were expecting that combining tar and pigz would somehow magically create a zip file with multiple entries, then no, that won't work. tar and zip are entirely different and unrelated formats. " 

isn't it possible to create PKWARE zip file using pigz (without tar) so it contain entire directory inside the .zip instead of tar.. " the idea is here to create a zip file using multiple cores to speed up the process "

I have researched a lot but the only format that is supported with entire Apple inc ecosystem is  PKWARE  zip.

**Comment by madler** [comment]
No. pigz can only create a zip file with a single entry.

The only thing I would recommend would be to use pigz on every file you want to put in the zip file individually, creating many one-entry zip files. Then use [zipknit](https://zlib.net/zipknit16.tar.gz) to combine them into a single zip file. The individual runs of pigz could be invoked using the [parallel command](https://www.gnu.org/software/parallel/), to run all of them in parallel.

**Comment by KupQ** [comment]
> No. pigz can only create a zip file with a single entry.
> 
> The only thing I can recommend would be to use pigz on every file you want to put in the zip file individually, creating many one-entry zip files. Then use [zipknit](https://zlib.net/zipknit16.tar.gz) to combine them into a single zip file. The individual runs of pigz could be invoked using the [parallel command](https://www.gnu.org/software/parallel/), to run all of them in parallel.

Mr.Adler
Thank you this is very help full.

One last question is it possible to decompress single entry as is? 
e.g: 

I use following command to create a PKWARE zip of myDirectory which store inside signle entry. 
tar -cv -I 'pigz --zip' -f archive.tar.zip myDirectory/

and i use following command to decompress it, but the output turns out to be " myDirectory " after decompression. 
tar -xv -I 'pigz --zip' -f archive.tar.zip 

is it possible decompress it and get the single entry "-" file instead of myDirectory ? 

Thank you.

**Comment by madler** [comment]
`pigz -dK < archive.tar.zip > archive.tar`
