### ISSUE TITLE
pigz errors out with zlib-1.3 ("zlib version less than 1.2.3")

### ISSUE THREAD

**Issue by thesamesam** [madler/pigz#111]
With the freshly-related zlib-1.3, I get:
```shell
$ pigz --version
pigz: abort: zlib version less than 1.2.3
```

This is with pigz-2.7.

The check is at https://github.com/madler/pigz/blob/cb8a432c91a1dbaee896cd1ad90be62e5d82d452/pigz.c#L4638 and looks like a false positive, given the comments adding it mention just needing a minimum of 1.2.3. The perils of digits and version comparison.

**Comment by madler** [comment]
Wow, that was fast! Thank you for the report. Fixed in https://github.com/madler/pigz/commit/907ca0763be4547a9b0cce8c1057217488149744

**Comment by thesamesam** [comment]
Thanks!

**Comment by iz8mbw** [comment]
Hello. Just for your info, I have had Docker image extraction issue (since Docker uses "unpigz").
On my Linux System I have zlib 1.3 built from source code in "/usr/local/lib" and unpigz (pigz 2.6) was not able to run due to "unpigz: abort: zlib version less than 1.2.3".

**Comment by madler** [comment]
@iz8mbw Um, yeah. That's exactly what was fixed by the commit above, two months ago. You should be using pigz 2.8, not 2.6.

**Comment by iz8mbw** [comment]
Yes, but on that Linux system there's the default Ubuntu 22 version of pigz, so 2.6.
I mean I didn't build pigz from source code, I built only zlib, then I had this error

**Comment by madler** [comment]
If you can build zlib, you can build pigz.

**Comment by iz8mbw** [comment]
Sure. It's planned. 😀
