### ISSUE TITLE
Allow CFLAGS and LDFLAGS from environnement

### ISSUE THREAD

**Issue by ggardet** [madler/pigz#114]
Currently, the `Makefile` sets `CFLAGS` and `LDFLAGS` and ignore the values from environnement.
This is a problem for Linux distributions which use hardening/optimization flags for all packages.

Replacing `CFLAGS=xyz` with `CFLAGS?=xyz` and the same for `LDFLAGS` should do it.

**Comment by madler** [comment]
I'll add that. Thanks.

**Comment by ggardet** [comment]
Ping.

**Comment by madler** [comment]
This change has been applied to my local copy. I will push that and other updates once I have enough to warrant a new version.

**Comment by madler** [comment]
I have pushed my local commits to the develop branch here.

**Comment by billatarm** [comment]
@madler I am at the tip of development branch fe4894f577, and I don't see any changes to the Makefile to support environment defined flags, did I miss something?

**Comment by madler** [comment]
@billatarm  https://github.com/madler/pigz/commit/5df57d7e53020aaa5bdec5e5d21a104de841543e

**Comment by billatarm** [comment]
Can confirm this works, thanks for the fast response @madler . Do you have any idea when this will land on a release?

**Comment by madler** [comment]
Once there are enough improvements in my mind to warrant a new version.

**Comment by billatarm** [comment]
Sometimes, with fairly stable projects, the amount of delta is low but downstream still needs the updates. So you may never get to the non-quantitative state of "this is enough changes". It's been almost a year since a release and downstream could use a release. Specifically the Makefile changes affect packaging for distros like Fedora.
