### ISSUE TITLE
Don't abort when recursive

### ISSUE THREAD

**Issue by nemobis** [madler/pigz#14]
On pigz -drv:

c/ch/chillsonicfanon_pages_full.xml.gz to c/ch/chillsonicfanon_pages_full.xml pigz abort: corrupted input -- invalid deflate data: c/ch/chillsonicfanon_pages_full.xml.gz

Correct, because gunzip agrees:

$ gunzip c/ch/chillsonicfanon_pages_full.xml.gz
gzip: c/ch/chillsonicfanon_pages_full.xml.gz: unexpected end of file

But it's quite annoying because I expect the directory to be all uncompressed and instead I have all the following files still compressed.

**Comment by madler** [comment]
Fixed in develop branch.

**Comment by nemobis** [comment]
Mark Adler, 22/01/2015 08:58:
> Fixed in develop branch.

Great! Thanks.
