### ISSUE TITLE
after compressing > 500 GB tar output from stdin pigz gets stuck with massive CPU usage and no I/O activity

### ISSUE THREAD

**Issue by krichter722** [madler/pigz#17]
I'm creating a gunzipped tarball of ~3M files with 720 GB of an ext4 partition with 

```
sudo tar cf - to_compress/ | pigz -p 16 > /path/to/compressed.tar.gz
```

After > 500 GB `pigz` gets stuck using > 90 % of CPU with no observable I/O activity (`iotop`). Shouldn't `gunzip` and therefore also `pigz` read data continuously? Changing the number threads doesn't change (I only changed once because the test takes some time...). Are you testing for such large input data sets?

experienced with pigz 1c9c03b8cb1d812815fc6b0d4b48eeea5c203b7c and 2.2.4 on Ubuntu 13.10.

**Comment by madler** [comment]
Unable to reproduce.
