### ISSUE TITLE
gcc warning with hardening flags

### ISSUE THREAD

**Issue by Code7R** [madler/pigz#21]
I think it expects sensible handling of the return code...
```
cc -O3 -Wall -Wextra -D_FORTIFY_SOURCE=2  -c -o zopfli/src/zopfli/katajainen.o zopfli/src/zopfli/katajainen.c
pigz.c: In function ‘copymeta’:
pigz.c:3399:5: warning: ignoring return value of ‘chown’, declared with attribute warn_unused_result [-Wunused-result]
     (void)chown(to, st.st_uid, st.st_gid);
     ^
```

**Comment by madler** [comment]
I put in a (void) to make it explicit that I had consciously decided to ignore the return code.  That should not generate a warning.

**Comment by Code7R** [comment]
And it should please also consider the LDFLAGS from environment. Proposal:
```
diff --git a/Makefile b/Makefile
index 6524ef3..f7f6191 100644
--- a/Makefile
+++ b/Makefile
@@ -1,6 +1,6 @@
 CC=cc
 CFLAGS=-O3 -Wall -Wextra
-LDFLAGS=-lz
+LDFLAGS+=-lz
 ZOPFLI=zopfli/src/zopfli/
 # use gcc and gmake on Solaris
 
```

**Comment by Code7R** [comment]
Sorry, (void) doesn't help here. I had to find a workaround in one of my projects for this check. Quote:
```

// STFU helpers, (void) casts are not effective for certain functions
static inline void ignore_value (int i) { (void) i; }
static inline void ignore_ptr (void* p) { (void) p; }

```

**Comment by madler** [comment]
You only got a warning for chown?

**Comment by madler** [comment]
Your suggestion for += in the Makefile is a different issue.  You should create a new issue for that, and not mix it up with voided return codes.

**Comment by Code7R** [comment]
Yes, only this one. For example, see https://buildd.debian.org/status/fetch.php?pkg=pigz&arch=i386&ver=2.3.3-1&stamp=1422210364 .

Regarding += issue, that one is partially related, at least from my perspective. This style of value assignment (and gmake's lazy initialization rules) prevented the hardening flags from being passed. I used a workaround in the meantime (pushing CPPFLAGS/LDFLAGS/etc. from the make command line) and it's OK, so no new item related to that for now.

**Comment by madler** [comment]
Then it's a bug in the compiler.  The behavior should be consistent with all of the other occurrences of voided return values, such as the chmod() and utimes() in the same routine, and the other dozen or more times int return values are voided in pigz.c.  Either all of them should get the warning, or none of them should.
