### ISSUE TITLE
Error while installation (zlib linkage) on Linux

### ISSUE THREAD

**Issue by sidorov-si** [madler/pigz#33]
Hi!

I tried to compile the current version of pigz (2.3.3) on Ubuntu 14.04 and bumped into the following error:

`cc -lz -o pigz pigz.o yarn.o try.o zopfli/src/zopfli/deflate.o zopfli/src/zopfli/blocksplitter.o zopfli/src/zopfli/tree.o zopfli/src/zopfli/lz77.o zopfli/src/zopfli/cache.o zopfli/src/zopfli/hash.o zopfli/src/zopfli/util.o zopfli/src/zopfli/squeeze.o zopfli/src/zopfli/katajainen.o -lpthread -lm
pigz.o: In function 'outb_check':
pigz.c:(.text+0x4b9): undefined reference to 'crc32'
pigz.c:(.text+0x531): undefined reference to 'adler32'
[...]`

I can see that zlib linkage flag `-lz` is put at the very beginning of the `cc` command, because `$(LDFLAGS)` is put there in the Makefile:

`pigz: pigz.o yarn.o try.o ${ZOPFLI}deflate.o ${ZOPFLI}blocksplitter.o ${ZOPFLI}tree.o ${ZOPFLI}lz77.o ${ZOPFLI}cache.o ${ZOPFLI}hash.o ${ZOPFLI}util.o ${ZOPFLI}squeeze.o ${ZOPFLI}katajainen.o
	$(CC) $(LDFLAGS) -o pigz $^ -lpthread -lm
	ln -f pigz unpigz
`

But, as I understand, `-lz` should be put at the very end of the command on Linux. Makefile with the following command works without a problem:

`pigz: pigz.o yarn.o try.o ${ZOPFLI}deflate.o ${ZOPFLI}blocksplitter.o ${ZOPFLI}tree.o ${ZOPFLI}lz77.o ${ZOPFLI}cache.o ${ZOPFLI}hash.o ${ZOPFLI}util.o ${ZOPFLI}squeeze.o ${ZOPFLI}katajainen.o
	$(CC) -o pigz $^ -lpthread -lm $(LDFLAGS)
	ln -f pigz unpigz`

Probably, it would be great to add some check to the Makefile to put `$(LDFLAGS)` to the end of the `cc` command when compiling on Linux.

Best regards,
    Svyatoslav

**Comment by gsaksena** [comment]
The Makefile works as-is on RHEL6 and Debian7 Wheezy backports, but fails on Ubuntu 14.04.  Changing the Makefile to move the $(LDFLAGS) to the end fixes it on Ubuntu 14.04.

cat Makefile | sed 's/$(CC) $(LDFLAGS) -o pigz $^ -lpthread -lm/$(CC) -o pigz $^ -lpthread -lm $(LDFLAGS)/' > Makefile2

**Comment by madler** [comment]
Fixed in 2.3.4.
