### ISSUE TITLE
Pigz/gzip IO bounded

### ISSUE THREAD

**Issue by iNDicat0r** [madler/pigz#34]
Hi

I understand that compression algorithms are CPU and IO bounded however CPU is being utilised much more. Is there any performance gains with pigz since reading data will make the IO device the actual bottleneck? It sounds more logical to gain some performance on SSDs but not on normal HDs? Could you please elaborate?

**Comment by madler** [comment]
This is not a development issue with pigz.

**Comment by iNDicat0r** [comment]
I know its not a dev issue but the question remains unanswered for those including myself who want to use this for particular use cases.

**Comment by madler** [comment]
Try one of the stackexchange.com sites for this question. Also your question a) can't be answered generically since it depends on the hardware, and b) can be answered easily for your hardware simply by trying it.

**Comment by iNDicat0r** [comment]
Alright Mark I will check myself! Btw I think you need an up to dated website;) let me know if you are interested, I will donate domain and server resources if u need!
