### ISSUE TITLE
Corrupted zip output

### ISSUE THREAD

**Issue by noname440** [madler/pigz#35]
I'm having an issue when trying to create a zip archive. I have a specific file that when I compress using the -K option cannot be uncompressed afterwards. I get a CRC failure message. 
I don't receive any error messages during compression.
I can compress the file fine using 7zip.
I can compress to gz format using pigz without issue.
The file is over 5 gigabytes.
I'm using RHEL v 6.8 (Santiago) on a x86_64 machine.

**Comment by madler** [comment]
pigz does not yet support the Zip64 extensions to the zip format for >= 4 GB entries.

**Comment by madler** [comment]
For now I have added a warning message when using -K on >= 4 GiB entries, that the output will be unusable.

**Comment by madler** [comment]
This commit: https://github.com/madler/pigz/commit/4079828fae8f1bf5fb2cee66d805fc758d67046f supports the Zip64 format for large inputs.

**Comment by noname440** [comment]
Do you have a planned date for this to be in a release?

**Comment by madler** [comment]
No. I will wait until I have some more substantial changes. If you need it, you can just download the Develop version. https://github.com/madler/pigz/archive/develop.zip
