### ISSUE TITLE
how to zip a folder

### ISSUE THREAD

**Issue by miranos** [madler/pigz#37]
Hi

Many days ago i tried to look for a way to modify the code in order to compress a diretory !

Have you an idea on how to process please ?

Thank's.

**Comment by madler** [comment]
The gzip format only stores a single stream of data, e.g. a single file. You can use tar to create a single stream of data from a tree of directories and files, along with the structure, names, attributes, etc. and then compress that with pigz. This makes the commonly seen ".tar.gz" files.

**Comment by miranos** [comment]
I want use another method, i already know this ... i want integrate a piece of code that will do same thing.

Since i am using a windows version.
