### ISSUE TITLE
add parallel uncompress support via --index option

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [madler/pigz#40]
please: https://github.com/mgerdts/pigz/commit/fe9c1ed5cea290b286f8de62aecbad4b970dc980

**Comment by madler** [comment]
I am considering a different scheme that does not require an index.

**Comment by kulikjak** [comment]
Hi, FYI in case you are interested, we recently rebased the original [mgerdts@fe9c1ed](https://github.com/mgerdts/pigz/commit/fe9c1ed5cea290b286f8de62aecbad4b970dc980) change onto pigz 2.8.

https://github.com/oracle/solaris-userland/blob/32b9b853f273800c7d5d6a5b1a4d04717fc71d63/components/pigz/patches/202_index.patch
