### ISSUE TITLE
 pigz abort: corrupted input -- invalid deflate data

### ISSUE THREAD

**Issue by payals** [madler/pigz#44]
Trying to decompress a backup (tar.gz) with pigz and getting this error. When I disable parallelization with -dp1, I still get the same error. However, I can decompress the file successfully with gunzip or tar -xvzf. pigz is the only tool that fails on decompression of this file. However, all the other backups decompress with pigz, it is just this particular backup file. The fact that other decompression algorithms work fine makes me wonder if this might be a bug in pigz? The pigz version is 2.1.6.

**Comment by madler** [comment]
Can you provide a link to download the file?

**Comment by payals** [comment]
I'm sorry its a database backup file, so I can't. I understand if this cannot be debugged without the problem file in question. Feel free to close the issue. FWIW I'm currently testing decompression with pigz 2.3.4 and see this:

psingh@jdw1:~/pigz-2.3.4$ ./pigz -dc ../db2-data-2017-03-02.tar.gz > /tmp/decompression/backup 
pigz: skipping: ../db2-data-2017-03-02.tar.gz: corrupted -- invalid deflate data (invalid distances set)
pigz: abort: internal threads error

**Comment by madler** [comment]
Without an example, there is nothing I can do.

**Comment by davebdb** [comment]
I'm having similar issues and can send you some files.  Is there a way I can get the files to you OFF of github though?  i.e Give you a link to download from via an email.

However it seems somewhat inconsistent.  For 3 times in a row it failed on the same file, but now its failing on another file.

**Comment by madler** [comment]
Sure. You can send an email with links to zlib at madler dot net.

**Comment by davebdb** [comment]
Info sent.
