### ISSUE TITLE
Build against zlib-ng library

### ISSUE THREAD

**Issue by vielmetti** [madler/pigz#45]
There is a project `zlib-ng` to do a faster single-threaded zlib. 

There's interest in seeing how the `pigz` code might be sped up by incorporating code or libraries from `zlib-ng`, expressed at https://github.com/Dead2/zlib-ng/issues/96

Cross-linking those two ideas, here; I have not started to try to see how the build would change to use that other library.

**Comment by cieplutki** [comment]
I have tried it and it's not trivial. It works under linux, no problem, but under windows it causes segfault I tried to debug but didn't solve it yet. So if you want to use it under linux it's pretty straightforward - configure with *--zlib-compat* option and compile zlib-ng, then link pigz against that library and that should be it.
If you do share your impressions.

**Comment by neurolabusc** [comment]
@vielmetti please see this [pigz fork](https://github.com/neurolabusc/pigz) for Linux and MacOS. I uses a CMake script from @ningfei that allows you to compile pigz for the System, [Cloudflare](https://github.com/cloudflare/zlib) or [zlib-ng](https://github.com/zlib-ng/zlib-ng).  My [benchmark](https://github.com/neurolabusc/pigz-bench) includes a shell script that will compile all three variants, and demonstrates that at the moment CloudFlare is superior. We hope to generate a pull request with the [CMake](https://github.com/madler/pigz/issues/62) version, but need to finalize the build for the Windows operating system.
