### ISSUE TITLE
pigz deletes files

### ISSUE THREAD

**Issue by lkuchenb** [madler/pigz#46]
I was just trying out whether an in-place compression is possible using `pigz -S ''` - it turns out pigz just follows its usual workflow, i.e. it compresses and then unlinks the original. Which in this case is the same as the target.

```
$ echo "hello world" > testfile
$ pigz -S '' -f testfile && echo OK
OK
$ ls
$
```

No error return code and even worse, the data is gone.

For the record, I then tried `gzip` and it ignores `-S ''` and behaves as if `-S` wasn't specified.

**Comment by madler** [comment]
Fixed in next version.

**Comment by pavel-odintsov** [comment]
Hello!

Can you provide reference to commit where it was fixed and version, please?

I tried it on 2.3.4-1 from Debian Stretch and it still deletes original and target file.

Thank you!
