### ISSUE TITLE
Please upload maintainer-generated tarballs to github

### ISSUE THREAD

**Issue by rossburton** [madler/pigz#53]
The github-generated tarballs can and do change over time (as they're generated on demand using git-archive) so they're not useful for distributions which perform integrity checks on downloaded tarballs.

Only the latest tarball is available on zlib.net, for example https://zlib.net/pigz/pigz-2.4.tar.gz is present but https://zlib.net/pigz/pigz-2.3.4.tar.gz doesn't exist anymore.

Please consider uploading the generated tarballs to github and associating them with the releases as a persistent archive of the official tarballs.

**Comment by Code7R** [comment]
Btw, if space is an issue, you could also consider using pristine-tar.

**Comment by madler** [comment]
They're all still there in http://zlib.net/pigz/fossils/ .

**Comment by rossburton** [comment]
All I'm asking for is a single URL that refers to a stable tarball of each release of pigz.

I can't use http://zlib.net/pigz/pigz-2.4.tar.gz as the moment 2.4.1 is released that URL is a 404.

I can't use /pigz/fossils/ as 2.4 isn't in there yet.

I can't use the GitHub tarball links as they're generated on demand and do change over time.

Simply adding the latest release each time into /fossils/ would be sufficient.

**Comment by madler** [comment]
2.4.1? There is no 2.4.1 yet.

**Comment by rossburton** [comment]
That was the point.  If my metadata says "download pigz 2.4 from http://zlib.net/pigz/pigz-2.4.tar.gz" and you release a 2.4.1, that URL won't exist anymore.  The same way our metadata until recently used to say "download 2.3.4 from http://zlib.net/pigz/pigz-2.3.4.tar.gz" but that failed when 2.4 was released as (I now know) the 2.3.4 tarball goes into /fossils/.

A single directory which contains all releases, past and present, means there are stable URLs which we can use now and in the future without worry.

**Comment by madler** [comment]
The stable link is https://zlib.net/pigz/pigz.tar.gz , which will download the latest version.

**Comment by rossburton** [comment]
Sorry I wasn’t clear: a stable URL for a specific release.

**Comment by madler** [comment]
Ok, I put 2.4 in fossils as well.

**Comment by rossburton** [comment]
Thanks, that will work!
