### ISSUE TITLE
windows fsync() for porting

### ISSUE THREAD

**Issue by cieplutki** [madler/pigz#54]
I tried to compile pigz on windows (mingw) and successfully done it with some effort but the solution turned out to be simple - implement fsync() using windows native functions. I attach patch file so you can check it out. Hope you will find it useful. There are two versions of fsync() - one using FlushFileBuffers() and second using _commit(). You can choose whichever you find appropriate- there seem to be no difference in performance. Files are somewhat excessively commented so should be no problem reading them.
Both versions of fsync() work well - I tested them on over 6k+ files of all sizes - from 1B to 6GiB. Compressed, tested with gzip and pigz and decompressed to make sure they are not corrupted and they were fine.
Hope you will like it and use it in future release.
[pigz-2.4.win_fsync-2.diff.gz](https://github.com/madler/pigz/files/1904492/pigz-2.4.win_fsync-2.diff.gz)

**Comment by madler** [comment]
Will use `_commit()` on Windows.
