### ISSUE TITLE
Improved error message when running without terminal and compressed file already exists

### ISSUE THREAD

**Issue by skjaeve** [madler/pigz#55]
When running pigz without a terminal (for example via crontab) and a compressed file already exists, it's not possible for pigz to ask the user to overwrite or not. This  causes pigz to fail with an error message:

pigz: abort: write error on 001.txt.gz (Inappropriate ioctl for device)

It would be more useful with something along the lines of

pigz: abort: compressed file exists: 001.txt.gz
or perhaps better?
pigz: skipping 001.txt: compressed file exists: 001.txt.gz

It would also be useful to have a --no-overwrite option.

pigz 2.4, Fedora 27, x64

**Comment by MedAlch** [comment]
Hi, same issue two years later, this is causing our logging server to crash due to full disk usage...

**Comment by madler** [comment]
@skjaeve  pigz is using `isatty()` to determine whether or not to query the user. Somehow your systems are telling pigz it is talking to a terminal when it isn't.

@MedAlch I don't understand how skjaeve's issue would result in full disk usage. pigz is quitting after one message. What exactly is your issue with a log file that is filling the disk? What is in the log file?

**Comment by MedAlch** [comment]
Hi Mark,
I got the same error than @skjaeve when running pigz by hand to troubleshoot our disk usage and I faced the same problem. As you mention, if pigz skips this message in TTY mode, the issue might be something else.

Thank you for taking the time to answer us.

**Comment by madler** [comment]
I have nevertheless cleaned up the logic for the overwrite request in this commit: https://github.com/madler/pigz/commit/7385d929b5dfd5cd6d26bdfdab6810d9e3a36d1b
