### ISSUE TITLE
lock order inversion

### ISSUE THREAD

**Issue by coypoop** [madler/pigz#60]
that can be a deadlock. via tsan (going by memory, I hope I am not mis-remembering)

pigz.c:1458
```
    possess(space->use);
    use = peek_lock(space->use);
    assert(use != 0);
    if (use == 1) {
        pool = space->pool;
        possess(pool->have);
```
pigz.c:1399
```
    possess(pool->have);
    if (pool->limit == 0)
        wait_for(pool->have, NOT_TO_BE, 0);

    // if a space is available, pull it from the list and return it
    if (pool->head != NULL) {
        space = pool->head;
        possess(space->use);
```

**Comment by madler** [comment]
Thank you for the report. Fixed in https://github.com/madler/pigz/commit/1e847e68cc96f311b15bb091ce5b9b20d110e37f .

**Comment by Code7R** [comment]
Side issue: do you think this fix is important enough to cherry-pick into next Debian Stable (to be released soon)?

**Comment by madler** [comment]
Your call. Over the many years this problem has been laying in wait, I have had only one report of a hang in pigz that _might_ have been due to this.
