### ISSUE TITLE
Is there a way to make pigz output checksum-equal to gzip?

### ISSUE THREAD

**Issue by enunes** [madler/pigz#64]
I have been using pigz as a system-wide replacement to gzip for a while (as a gzip symlink earlier in PATH). I have been hitting an issue that pigz compressed files are not checksum-equal to those compressed by gzip.
In summary, for a project I work with, sha256 hashes are calculated for compressed tarballs, and I ended up submitting some hashes for tarballs I compressed with pigz, which resulted in them being different for users using gzip.
(for reference: https://patchwork.ozlabs.org/patch/975483/ )

I assume there are several reasons for why they are not exactly the same, but is there a way to make it so? I tried a few values for blocksize with pigz, used --no-name to avoid timestamps, but that didn't help. The number of threads doesn't seem to make a difference. Is there some parameter set or condition to make the result exactly the same as it would be with gzip?

**Comment by madler** [comment]
Nope. Not possible. gzip uses a different implementation of deflate.
