### ISSUE TITLE
File with multiple text file

### ISSUE THREAD

**Issue by k2kemp** [madler/pigz#67]
Is there a way to use pigz with a Zip File with multiples text files inside ?

Example of my testing
pigz -dc file.zip | awk '{print $3}' | sort | uniq -c
pigz: warning: file.zip: entries after the first were ignored

Only one file seem to be extract.

**Comment by madler** [comment]
No. pigz only supports extracting the first file in a zip file, as well as compressing only one file to a zip file. You'd need to use unzip to extract other files.
