### ISSUE TITLE
Internal Threads Error on SLES 15

### ISSUE THREAD

**Issue by levi-dot** [madler/pigz#68]
Hello,
 
on my server (Xeon 8164, Suse Linux Enterprise 15, HP ProLiant DL380 Gen10).

When I use pigz and specify the number of threads (4 in this example)
`zcat AmP1_R1.fastq.gz | pigz -p 4 > out.fastq.gz `

I get this error (5 out of 10 times):
`pigz: abort: internal threads error`

Strace log says:

```
write(1, "T\nTCACCGTGCCAGACTAGAGTCAAGCTCAAC"..., 32644) = 32644
read(10, "\254Ml@\344\300\351;\216%\356\v\253Ce\26Q\306\250\324\265\f\350\312\362\301 #F\353\313\341"..., 32768) = 32768
pigz: abort: internal threads error
write(1, "@NB551369:35:H3VGYBGX9:2:21304:1"..., 32768) = 32768
write(1, "ATGCCTCGTCATCTAATTAGTGACGCGCATGA"..., 32638) = 32638
write(1, "@NB551369:35:H3VGYBGX9:2:21304:1"..., 32768) = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=67738, si_uid=1030} ---
rt_sigprocmask(SIG_BLOCK, [HUP INT PIPE TERM XCPU XFSZ], [HUP INT PIPE TERM XCPU XFSZ], 8) = 0
rt_sigprocmask(SIG_SETMASK, [HUP INT PIPE TERM XCPU XFSZ], NULL, 8) = 0
rt_sigaction(SIGPIPE, {sa_handler=SIG_DFL, sa_mask=[PIPE], sa_flags=SA_RESTORER|SA_RESTART, sa_restorer=0x7fb5a0713160}, {sa_handler=0x55bc0c4beb2c, sa_mask=[HUP INT PIPE TERM XCPU XFSZ], sa_flags=SA_RESTORER, sa_restorer=0x7fb5a0713160}, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [HUP INT PIPE TERM XCPU XFSZ], 8) = 0
getpid()                                = 67738
gettid()                                = 67738
tgkill(67738, 67738, SIGPIPE)           = 0
rt_sigprocmask(SIG_SETMASK, [HUP INT PIPE TERM XCPU XFSZ], NULL, 8) = 0
rt_sigreturn({mask=[]})                 = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_TKILL, si_pid=67738, si_uid=1030} ---
+++ killed by SIGPIPE +++
```

If I dont specify the number of threads, it runs like a charm. 
Also a different zip-tool like pbzip2 doesn't have any problem at all. 
Prime95 runs without any problems for 24h, no bad sector detected, ram has been tested and is okay.
I think there is no hardware-failure.
Also, on another server (same Software and OS - different hardware), there is no problem at all.

Can you help me with this issue? 

Thanks

**Comment by madler** [comment]
Interesting. What version of pigz are you using? Do you have the ability to recompile pigz? How does it behave with -p values other than 4?

**Comment by MithrasXO** [comment]
Hello and thanks for the reply:

I used 2.4 and 2.3.3, same issue with both.

I tried with 2 and 8 threads as well, same error. Example:

```
zcat AmP1_R1.fastq.gz | pigz_tmp -p 2 > out.fastq.gz 
pigz_tmp: abort: internal threads error
```


Yeah I did recompile pigz, same behavior (tried with (default) gcc 7.3 and gcc 8.2.1) here is the make-log:

```
northoff@klc253c5:~/martin/pigz-master> make
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas   -c -o pigz.o pigz.c
In file included from pigz.c:412:
pigz.c: In function ‘option’:
try.h:422:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 #define TRY_THROW_(...) try_throw_(__VA_ARGS__, NULL)
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
try.h:269:15: note: in expansion of macro ‘TRY_THROW_’
 #define throw TRY_THROW_
               ^~~~~~~~~~
pigz.c:4218:17: note: in expansion of macro ‘throw’
                 throw(EINVAL, "invalid option: LZW output not supported: %s",
                 ^~~~~
pigz.c:4220:13: note: here
             case 'a':
             ^~~~
In file included from pigz.c:412:
try.h:422:25: warning: this statement may fall through [-Wimplicit-fallthrough=]
 #define TRY_THROW_(...) try_throw_(__VA_ARGS__, NULL)
                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
try.h:269:15: note: in expansion of macro ‘TRY_THROW_’
 #define throw TRY_THROW_
               ^~~~~~~~~~
pigz.c:4221:17: note: in expansion of macro ‘throw’
                 throw(EINVAL, "invalid option: no ascii conversion: %s",
                 ^~~~~
pigz.c:4223:13: note: here
             case 'b':  get = 1;  break;
             ^~~~
pigz.c: In function ‘show_info’:
pigz.c:2900:9: warning: ‘strncpy’ specified bound depends on the length of the source argument [-Wstringop-overflow=]
         strncpy(tag, g.inf, n > max + 1 ? max + 1 : n);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
pigz.c:2899:13: note: length computed here
         n = strlen(g.inf) - compressed_suffix(g.inf);
             ^~~~~~~~~~~~~
pigz.c: In function ‘compress_thread’:
pigz.c:1624:19: warning: variable ‘temp’ might be clobbered by ‘longjmp’ or ‘vfork’ [-Wclobbered]
     struct space *temp = NULL;      // temporary space for zopfli input
                   ^~~~
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas   -c -o yarn.o yarn.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas   -c -o try.o try.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -c zopfli/src/zopfli/deflate.c
zopfli/src/zopfli/deflate.c: In function ‘OptimizeHuffmanForRle’:
zopfli/src/zopfli/deflate.c:399:24: warning: argument 1 range [18446744065119617024, 18446744073709551612] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
   good_for_rle = (int*)malloc(length * sizeof(int));
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from zopfli/src/zopfli/zopfli.h:24,
                 from zopfli/src/zopfli/deflate.h:28,
                 from zopfli/src/zopfli/deflate.c:20:
/usr/include/stdlib.h:424:14: note: in a call to allocation function ‘malloc’ declared here
 extern void *malloc (size_t __size) __THROW __attribute_malloc__ __wur;
              ^~~~~~
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -c zopfli/src/zopfli/blocksplitter.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -c zopfli/src/zopfli/tree.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -c zopfli/src/zopfli/lz77.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -c zopfli/src/zopfli/cache.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -c zopfli/src/zopfli/hash.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -c zopfli/src/zopfli/util.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -c zopfli/src/zopfli/squeeze.c
gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -c zopfli/src/zopfli/katajainen.c
gcc  -o pigz pigz.o yarn.o try.o deflate.o blocksplitter.o tree.o lz77.o cache.o hash.o util.o squeeze.o katajainen.o -lm -lpthread -lz
ln -f pigz unpigz
northoff@klc253c5:~/martin/pigz-master> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib64/gcc/x86_64-suse-linux/8/lto-wrapper
OFFLOAD_TARGET_NAMES=hsa:nvptx-none
Target: x86_64-suse-linux
Configured with: ../configure --prefix=/usr --infodir=/usr/share/info --mandir=/usr/share/man --libdir=/usr/lib64 --libexecdir=/usr/lib64 --enable-languages=c,c++,fortran,ada,go --enable-offload-targets=hsa,nvptx-none=/usr/nvptx-none, --without-cuda-driver --enablehecking=release --disable-werror --with-gxx-include-dir=/usr/include/c++/8 --enable-ssp --disable-libssp --disable-libvtv --disable-cet --disable-libcc1 --disable-plugin --with-bugurl=http://bugs.opensuse.org/ --with-pkgversion='SUSE Linux' --with-slibdir=/lib64 --th-system-zlib --enable-__cxa_atexit --enable-libstdcxx-allocator=new --disable-libstdcxx-pch --enable-version-specific-runtime-libs --with-gcc-major-version-only --enable-linker-build-id --enable-linux-futex --enable-gnu-indirect-function --program-suffix=-8 --witut-system-libunwind --enable-multilib --with-arch-32=x86-64 --with-tune=generic --build=x86_64-suse-linux --host=x86_64-suse-linux
Thread model: posix
gcc version 8.2.1 20180831 [gcc-8-branch revision 264010] (SUSE Linux)
```

**Comment by madler** [comment]
But if you don't use the `-p` option at all, it works?

If you don't mind trying some things for me to see what's going on, we can start with this: please add `fprintf(stderr, "yarn error %d\n", err);` in the `cut_yarn()` function before the `throw()`, recompile, and recreate the error. Thanks.

**Comment by MithrasXO** [comment]
Sure, here you go:

```
zcat AmP1_R1.fastq.gz | ~/martin/pigz-master/pigz -p 4 > out.fastq.gz
yarn error 16
pigz: abort: internal threads error

```

**Comment by MithrasXO** [comment]
Sure, here is the output. And sorry wrong button on closing the issue.

```
zcat AmP1_R1.fastq.gz | ~/martin/pigz-master/pigz -p 4 > out.fastq.gz
yarn error 16
pigz: abort: internal threads error
```

**Comment by madler** [comment]
Great! Now please replace the second if statement in yarn.c's free_lock() function with:

```
    if ((ret = pthread_cond_destroy(&(bolt->cond))) != 0) {
        fprintf(stderr, "free_lock cond %d\n", ret);
        fail(ret);
    }
    if ((ret = pthread_mutex_destroy(&(bolt->mutex))) != 0) {
        fprintf(stderr, "free_lock mutex %d\n", ret);
        fail(ret);
    }

```
and recreate the error. Then swap those two if statement and repeat.

**Comment by MithrasXO** [comment]
Code looks like this now:

```
void free_lock(lock *bolt)
{
    int ret;


    if (bolt == NULL)
        return;
   if ((ret = pthread_cond_destroy(&(bolt->cond))) != 0) {
        fprintf(stderr, "free_lock cond %d\n", ret);
        fail(ret);
    }
    if ((ret = pthread_mutex_destroy(&(bolt->mutex))) != 0) {
        fprintf(stderr, "free_lock mutex %d\n", ret);
        fail(ret);
    }
    my_free(bolt);
}
```
Output:

```
zcat AmP1_R1.fastq.gz | ~/martin/pigz-master/pigz -p 4 > out.fastq.gz
free_lock mutex 16
yarn error 16
pigz: abort: internal threads error
```

Second version:
```
void free_lock(lock *bolt)
{
    int ret;


    if (bolt == NULL)
        return;
    if ((ret = pthread_mutex_destroy(&(bolt->mutex))) != 0) {
	fprintf(stderr, "free_lock mutex %d\n", ret);
	fail(ret);
	}   
     if ((ret = pthread_cond_destroy(&(bolt->cond))) != 0) {
	fprintf(stderr, "free_lock cond %d\n", ret);
	fail(ret);
	}
   
    my_free(bolt);
}
```

```
zcat AmP1_R1.fastq.gz | ~/martin/pigz-master/pigz -p 4 > out.fastq.gz
free_lock mutex 16
yarn error 16
pigz: abort: internal threads error
```

**Comment by madler** [comment]
Thank you. I'm wondering what number of processors it's using without the option. Please add the line: `fprintf(stderr, "%d processes\n", g.procs);` before the comment `// process command-line filenames` in `main()` in pigz.c.

**Comment by MithrasXO** [comment]
I think all 104... looks like it in htop.

Yep:

```
northoff@klc253c5:~/BioInf/analyses/RNA-Seq/MyTi/test> zcat AmP1_R1.fastq.gz | ~/martin/pigz-master/pigz  > out.fastq.gz
104 processes
```

**Comment by madler** [comment]
104? Holy cow. Do you know what kind of speedup do you get in that case? (If you haven't measured it, you don't need to -- I'm just curious.)

**Comment by MithrasXO** [comment]
lets find out, pigz 1:10 min (just tried - input file is 1,9gig), gzip  should be over 10 minutes

**Comment by madler** [comment]
Hmm. Only a factor of ten. Should be more. You have 26 real cores. It might be I/O bound.

Anyway, I'll get back to you later with more debugging. Thank you for your help.

**Comment by MithrasXO** [comment]
It's a dual CPU system with 2x E8164, so 2x26 = 52 real cores and 104 threads. 

Yeah I/O should be the limit. I can see in htop that the cores/threads are not fully utilized. I would assume the data can't get to the CPU fast enough.

With 4 threads, 4 cores/threads are fully utilized.

**Comment by madler** [comment]
You could try it with `-11`. I bet it wouldn't be I/O bound then.

**Comment by madler** [comment]
Please get http://zlib.net/pigz/pigz-test.tar.gz and recreate the problem with it. Thanks.

**Comment by MithrasXO** [comment]
You are right, with flag `-11` all cores are fully utilized, unfortunately gzip just offers the option of level 9 compression. So no benchmark here.

I testet the test-version:

```
northoff@klc253c5:~/BioInf/analyses/RNA-Seq/MyTi/test> zcat AmP1_R1.fastq.gz | ~/martin/pigz_test/pigz -p 4  > out.fastq.gz
free_lock mutex 16 job->calc
pigz: abort: internal threads error

```

**Comment by madler** [comment]
Ah. I should have mentioned that you can use `-p 1` with pigz to benchmark the single thread case.

**Comment by MithrasXO** [comment]
And I should have known that there is no mutex that can block with only one thread ;) 
here we go:

```
All threads:
real: 17m19,086s
```

```
One thread:
real:  2h and counting -> that will finish tomorrow I guess, I will update this post then.
```

**Comment by madler** [comment]
If it's working as well as it possibly could with all the hyper threads, it could take as long as 30 hours to complete with one thread.

**Comment by MithrasXO** [comment]
Finished... factor of 70!

Do you think the issue can be solved? Problem is, we have tool, `cutdapat ` https://github.com/marcelm/cutadapt which uses pigz internally with a  `-p 4 ` option that can't be changed.

**Comment by madler** [comment]
Thank you for the benchmark!

I'm still looking at the code trying to figure out how this can happen. Not seeing it yet.

A workaround for you might be to make the number of processors fixed and recompile. Just set `g.procs` to the number of processes you want before the comment `// process command-line filenames`.

**Comment by MithrasXO** [comment]
Thanks, I will do that on monday. Just let me know if I can provide you any more info.

**Comment by MithrasXO** [comment]
Hey, I did recompile with static 52 threads. Runs great so far and we can use the full computing capacity for our analysis at the moment. Thanks very much for the hint.

**Comment by MithrasXO** [comment]
Okay, seems that the threads are overtaking each other. If I add a print like this to the init/lock/unlock functions:
` fprintf(stderr, "INIT mutex %d\n", &(bolt->mutex));  `

like so:

```
lock *new_lock(long initial)
{
    int ret;
    lock *bolt;

    bolt = my_malloc(sizeof(struct lock_s));
    if ((ret = pthread_mutex_init(&(bolt->mutex), NULL)) ||
        (ret = pthread_cond_init(&(bolt->cond), NULL)))
        fail(ret);
    bolt->value = initial;
     
    **fprintf(stderr, "INIT mutex %d\n", &(bolt->mutex));**  

    return bolt;
}

void possess(lock *bolt)
{
    int ret;

    if ((ret = pthread_mutex_lock(&(bolt->mutex))) != 0)
        fail(ret);

   printf(stderr, "LOCK mutex %d\n", &(bolt->mutex));  

}

void release(lock *bolt)
{
    int ret;

    if ((ret = pthread_mutex_unlock(&(bolt->mutex))) != 0)
        fail(ret);
        
     **fprintf(stderr, "UNLOCK mutex %d\n", &(bolt->mutex));**

}

void twist(lock *bolt, enum twist_op op, long val)
{
    int ret;

    if (op == TO)
        bolt->value = val;
    else if (op == BY)
        bolt->value += val;
    if ((ret = pthread_cond_broadcast(&(bolt->cond))) ||
        (ret = pthread_mutex_unlock(&(bolt->mutex))))
        fail(ret);
        
        
    **fprintf(stderr, "UNLOCK mutex %d\n", &(bolt->mutex));**
     
}
```

called it like this:
`zcat AmP1_R1.fastq.gz | ~/martin/pigz-mod/pigz -p 4 -f > out.fastq.gz 2> test1.txt`

It works without any issue. Seems like they are slowing down the system enough to prevent a deadlock.

If I put it only in the  init OR lock OR unlock function, its not enough.

**Comment by MithrasXO** [comment]
A test with 100 runs revealed that I still got around 4 mutex-errors, much better compared to 50/100 but still not really good.

**Comment by madler** [comment]
I fixed remedied an unrelated lock-order inversion, but it wouldn't hurt for you to try it. You can download https://github.com/madler/pigz/archive/develop.zip .

**Comment by MithrasXO** [comment]
I testet this Version, here is the output:

```
pigz: can't destroy locked resource (pigz.c:1916:mutex_destroy).
pigz: abort: internal threads error
```

I created a version that ignores this error (not really the correct way but anyway). It works, the files are OK and can be decompressed. There is no difference to the original file. I created a loop and tested it with 100 runs.

Code looks like this:

```
void free_lock(lock *bolt)
{
    int ret;

    if (bolt == NULL)
        return;

    if ((ret = pthread_cond_destroy(&(bolt->cond))) != 0) 
    {
        fprintf(stderr, "ERROR DESTROY cond %d\n", ret);
        fail(ret);
    }
    if ((ret = pthread_mutex_destroy(&(bolt->mutex))) != 0) 
    {
		if(ret == 16)
			fprintf(stderr, "pthread_mutex_destroy 16 EBUSY -> Warning SKIPPING! %d\n", ret);
		else
			fail(ret);
    } 
    my_free(bolt);
}
```

**Comment by madler** [comment]
Still not seeing it.

If you can, please download again https://github.com/madler/pigz/archive/develop.zip , compile it with `make pigzt` and use `pigzt` with the `-vv` option to send thread debugging output to stderr. There may be a lot of output to stderr. If the failure reoccurs, please save the output and make it available here.

It is possible that the addition of the log information will change the timing and result in not being able to reproduce the problem. Please also let me know if that happens. In that case, there is no need to make the log available.

Thanks.

**Comment by MithrasXO** [comment]
Hello Mark, thanks for the reply. I hope I did everything the right way, because I don't have much output, but there is an error (right now the server is quite busy doing something else).

` zcat AmP1_R1.fastq.gz | ~/martin/pigz-develop/pigzt -vv -p 4 -f > out.fast.gz`

```
<stdin> to <stdout> pigzt: pigz.c:631: insert_track: Assertion `mem->have < MAXMEM && "increase MAXMEM in source and try again"' failed.
Aborted (core dumped)
```

Should I increase the macro MAXMEM?

**Comment by madler** [comment]
Thanks! Yes, you'll need to increase `MAXMEM`. The debugging turns on a memory allocation tracker, which has a fixed-length buffer for the pointers.

**Comment by MithrasXO** [comment]
Hello Mark, 

sorry for the delayed answer I had some stuff to do. But here we go:

[pigz_log.txt](https://github.com/madler/pigz/files/3088523/pigz_log.txt)

**Comment by madler** [comment]
Thanks. What number of processors was pigz trying to use in that case?

**Comment by MithrasXO** [comment]
4 Threads

zcat AmP1_R1.fastq.gz | pigzt -vv -p 4 -f > out.fastq.gz

**Comment by GrantHov** [comment]
Is the issue fixed? I get the same error sometimes when running pigz with 10 cores on opensuse leap 15.

**Comment by MithrasXO** [comment]
Hey Grant, no it's not.

You could edit the program itself like shown below, I did not have any more issues since I modified it (it's a dirty hack tho).

```
void free_lock(lock *bolt)
{
    int ret;

    if (bolt == NULL)
        return;

    if ((ret = pthread_cond_destroy(&(bolt->cond))) != 0) 
    {
        fprintf(stderr, "ERROR DESTROY cond %d\n", ret);
        fail(ret);
    }
    if ((ret = pthread_mutex_destroy(&(bolt->mutex))) != 0) 
    {
		if(ret == 16)
			fprintf(stderr, "pthread_mutex_destroy 16 EBUSY -> Warning SKIPPING! %d\n", ret);
		else
			fail(ret);
    } 
    my_free(bolt);
}
```

**Comment by rpurdie** [comment]
I work on the Yocto Project and we compress build artefacts using pigz, often quite a lot of data by numbers of files and in parallel with many other running tasks.

Occasionally, on full builds we'll see a compression failure from pigz, for example in our CI:

https://autobuilder.yoctoproject.org/typhoon/#/builders/45/builds/792
https://autobuilder.yoctoproject.org/typhoon/#/builders/45/builds/792/steps/7/logs/step1b

but to jump to the issue:

| DEBUG: Executing shell function sstate_create_package
| pigz: abort: internal threads error (16, 720)
| tar: /srv/autobuilder/autobuilder.yoctoproject.org/pub/sstate/24/sstate:readline:core2-64-poky-linux-musl:8.0:r0:core2-64:3:241b1909d0f06ca48bda9ec41ccee543bb82fcc164b2b74cd4efd318b3ae0a33_package_write_ipk.tgz.KDjTwErb: Wrote only 8192 of 10240 bytes
| tar: Child returned status 16
| tar: Error is not recoverable: exiting now
| WARNING: /home/pokybuild/yocto-worker/musl-qemux86-64/build/build/tmp/work/core2-64-poky-linux-musl/readline/8.0-r0/temp/run.sstate_create_package.34356:1 exit 1 from 'exit 1'

This seems to happen on our openSuse 15.1 worker in particular, originally with the system provided 2.3.3 version.

I did patch a copy of pigz 2.4 and install it there to get more debug information and the above shows what I added.

It confirms that its aborting with errno 16, EBUSY and the 720 tells me it came from pthread_mutex_destroy(&(bolt->mutex)) in free_lock(), called from free_lock(job->calc).

Unfortunately this seems to be some race issue, it just occurs occasionally and we can't reproduce at will. The same task, re-executed will work second time.

I did look at the job->calc handling in the code and no problem jumps out at me. I did wonder if there was some kind of race between that and the thread shutdown/cleanup but I can't quite see it.

The other possibility is there is some bug with pthread handling on that system, it does seem to be specific to the Suse 15.1 system.

I'm now trying the same pigz code but with a different  libdl/libc/libpthread, just to see if I can isolate it to that. Its hard to know whether we've "fixed" it due to it being rare in our case (1 in 3 chance on a complete rebuild of the source which we try and avoid).

**Comment by madler** [comment]
@rpurdie You can use the latest develop version of pigz, https://github.com/madler/pigz/archive/develop.zip , which has some more specific error reporting.

**Comment by msmeissn** [comment]
SUSE currently has the thought it will likely be fixed by our just released glibc update that fixes some pthread weirdness tracked in upstream bug:

https://sourceware.org/bugzilla/show_bug.cgi?id=23275

**Comment by madler** [comment]
@MithrasXO @rpurdie Was this error remedied by the SuSE glibc fix mentioned by @msmeissn?

**Comment by levi-dot** [comment]
@madler I think it did. I did not get any new reports about pigz crashing on our newer servers with more recent SLES 15 versions.

Thanks for your support :)
