### ISSUE TITLE
version info prints to stderr, not stdout

### ISSUE THREAD

**Issue by planet36** [madler/pigz#71]
Version information is printed to stderr.  Please consider printing it to stdout instead.

https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html
GNU Coding Standards: --version
> The standard --version option should direct the program to print information about its name, version, origin and legal status, all on standard output, and then exit successfully.

**Comment by madler** [comment]
Fixed in https://github.com/madler/pigz/commit/c3de75bf0bcfeacf52d1d551c960483a7aa302e5 . Thanks.
