### ISSUE TITLE
Pigz decompression interrupted

### ISSUE THREAD

**Issue by kachroo** [madler/pigz#73]
Hi,

I was using pigz to decompress some large RNA-seq .gz files. There was an issue and the script was interrupted before pigz could finish decompression. Now in the same folder, I have a sample_1.fastq and sample_1.fastq.gz file. How do I complete the decompression without any loss of data? Please help. 

If I just re-run the pigz -d command, I get the following error:
pigz: abort: write error on sample_1.fastq (Invalid argument)

Priyanka

**Comment by madler** [comment]
Delete sample_1.fastq and try again.

**Comment by kachroo** [comment]
Hi,
Thanks a lot. I followed your advice and deleted the fastq files and reran pigz decompression. All files except one were decompressed. For that one file I get the following error, I'm not sure I understand what the issue is:

pigz: skipping: bf248_2_fltrd.fastq.gz: corrupted -- incomplete deflate data
pigz: abort: internal threads error

Priyanka

**Comment by madler** [comment]
If you can attach or link that file here, I can take a look at it.

**Comment by kachroo** [comment]
If you can share your email id I email you the link to my google drive. It is unpublished data.

**Comment by madler** [comment]
You can find my email address at the bottom of this page: http://zlib.net/

**Comment by kachroo** [comment]
Shared the dropbox link with you.

**Comment by madler** [comment]
Sorry. I think I deleted it as junk. Please resend the link.

**Comment by kachroo** [comment]
I just sent u an email with the link.

**Comment by madler** [comment]
The reported error "incomplete deflate data" is correct. That .gz file ends in the middle of the compressed data. (The file I downloaded was 9524531455 bytes in length.)

**Comment by asan-emirsaleh** [comment]
I have the same issue. I downloaded the file from NCBI FTP server using the Filezilla tool, and the file is ok. Unzipping has aborted with the message "pigz: skipping: GCF_018294505.1_IWGSC_CS_RefSeq_v2.1_genomic.fna.gz: corrupted -- invalid deflate data (invalid distance code)". I downloaded the same file once again, and faced the same error.

**Comment by madler** [comment]
I just downloaded that file from that server, and pigz extracted it with no errors. It is 4,338,081,367 bytes in length, with SHA-256 1dcc10aff3687802997d0778a3d8ea0a42f42bc49e0eb6b04df35937f7e15861 .

**Comment by asan-emirsaleh** [comment]
> I just downloaded that file from that server, and pigz extracted it with no errors. It is 4,338,081,367 bytes in length, with SHA-256 1dcc10aff3687802997d0778a3d8ea0a42f42bc49e0eb6b04df35937f7e15861 .

Thank you for engaging. I believe it be an issue with downloading. md5sum were incorrect. N>5 iterations of loading were performed, and finally the checksum matched. After that both gunzip and pigz worked well. Thank you again.

Best regards
Asan
