### ISSUE TITLE
Independent blocks with -p 1

### ISSUE THREAD

**Issue by timpalpant** [madler/pigz#74]
I was hoping to use `pigz --independent -p 1` to create gzipped files with independent blocks. As described in the manual:

> This also inserts an extra empty block to flag independent blocks by prefacing each with the nine-byte sequence (in hex): 00 00 FF FF 00 00 00 FF FF.

However, I can't seem to find these nine-byte sequences when combined with the flag `-p 1`. Is this intentional?

A small repro is:

```
timpalpant@linux:~$ pigz --version
pigz 2.4

timpalpant@linux:~$ head -c 10M < /dev/urandom > random.txt
timpalpant@linux:~$ pigz -i -p 1 < random.txt > random.p1.gz
timpalpant@linux:~$ pigz -i -p 2 < random.txt > random.p2.gz
timpalpant@linux:~$ ls -l random.*.gz
-rw-rw-r-- 1 timpalpant timpalpant 10489373 Dec  7 17:47 random.p1.gz
-rw-rw-r-- 1 timpalpant timpalpant 10489768 Dec  7 17:47 random.p2.gz
```

My use case is for log rotation, where I would like to generate gzipped files with independent blocks to facilitate random access, but don't really want log rotation compression to use more than one core on the machine.

**Comment by madler** [comment]
Not intentional. Sounds like a bug. I'll take a look.

**Comment by madler** [comment]
Yep, a bug. Fixed in the develop branch with this commit: https://github.com/madler/pigz/commit/501a95544ada9645b6ab5f7e71acb8303743a9ec .
