### ISSUE TITLE
Deviation from gzip: return status upon trailing junk

### ISSUE THREAD

**Issue by mschilli87** [madler/pigz#76]
If I run

```sh
wget -q http://distfiles.gentoo.org/distfiles/xmltex-1.9.tar.gz -O - \
| gzip -d \
> /dev/null \
&& echo good \
|| echo bad
```

I get:

```
good
```

However, running

```sh
wget -q http://distfiles.gentoo.org/distfiles/xmltex-1.9.tar.gz -O - \
| pigz -d \
> /dev/null \
&& echo good \
|| echo bad
```

I get

```
pigz: <stdin> OK, has trailing junk which was ignored
bad
```

*I.e.* `pigz` errors on the (faulty) file, while `gzip` happily returns success.

While one could argue what behaviour is better, but this causes errors on systems using `pigz` as a drop-in replacement for `gzip` that are hard to troubleshoot.
As long as `gzip` is the standard, I'd prefer `pigz` to model its behaviour.

The corresponding Gentoo bug is here: 
https://bugs.gentoo.org/645438

**Comment by madler** [comment]
Fixed in https://github.com/madler/pigz/commit/9696c84cb1963651707e649978afb07d0c11b254 .

**Comment by madler** [comment]
By the way, you should let the gentoo folk know that junk at the end of their tar.gz archives is a bug as well.

**Comment by mschilli87** [comment]
@madler: Yes, [they know since 2018](https://bugs.gentoo.org/645438#c6). :wink:
The main issue is that maintaines don't catch this with gzip but then some users (incl. me until yesterday) have pigz symlinked to gzip and can't build the package.
To circumvent this, maintainers could require gzip over pigz for their packages forcing users to use pigz explicitely on the shell and gzip by default / in scripts.
Now, thanks to you, once there is a new relearse  of pigz, they can instead require gzip or a minimum version of pigz to know that if things work on their test system, they won't break for the user. 

If I package something, I'll make sure to unpack it with `pigs -v` to catch bad archives. :smile:
