### ISSUE TITLE
Fixed in https://github.com/madler/pigz/commit/9696c84cb1963651707e649978afb07d0c11b254 .

### ISSUE THREAD

**Issue by stefangweichinger** [madler/pigz#80]
Fixed in https://github.com/madler/pigz/commit/9696c84cb1963651707e649978afb07d0c11b254 .

_Originally posted by @madler in https://github.com/madler/pigz/issues/76#issuecomment-578438435_

I am currently trying to debug some behavior with pigz in combo with Amanda backup suite.
There I have issues with detecting the end of an archive.

I use debian 10.6 and pigz 2.4 ... as far as I understand, that binary would not yet contain above patch, correct? If yes, is there a beta binary somewhere? Sorry for an FAQ, I will search around myself as well ... just wanted to file the issue to be able to reference it in a mailinglist later.

**Comment by stefangweichinger** [comment]
I managed to build a binary from your `develop` branch and started testing already.

**Comment by stefangweichinger** [comment]
Unfortunately my tests with pigz 2.4.1x didn't change much.

In the Amanda backup suite ( https://github.com/zmanda/amanda ) it's possible to use a custom compress program, and I use pigz for a while now to compress backups. Works fine.

The issue: if I have to restore from more than one tapes, there are several unpacking steps.
So the first part is read from tape and unzipped, and the process `amrecover` waits for pigz to finish properly.
It seems as if it stills behaves differently than gzip, the beta removes that "trailing junk" message, but never really terminates.

I am trying to find a solution here, maybe you have an idea. Thanks.

**Comment by madler** [comment]
I do not understand your report.

**Comment by madler** [comment]
No response in over a year. Closing.
