### ISSUE TITLE
error: pigz: abort: write error on <stdout> (Broken pipe)

### ISSUE THREAD

**Issue by shangyf-stu** [madler/pigz#82]
I am sorry to border you. But I met trouble when I use pigz. 
The version is 
    pigz 2.3.4. 
The command is 
    pigz -dc SRR7722937.fastq.gz | head | pigz > SRR7722937.1mio.check.fq.gz
Please give me some suggestions, there is great appreciate for you.

**Comment by madler** [comment]
Fixed with this commit: https://github.com/madler/pigz/commit/04cb4f31cdfc6cd12b0277332bf6d2160c5f8a2a
