### ISSUE TITLE
2.5 fails to build with Fedora 34 (rawhide)

### ISSUE THREAD

**Issue by rosset** [madler/pigz#86]
Start: rpmbuild pigz-2.5-1.fc34.src.rpm
Building target platforms: x86_64
Building for target x86_64
setting SOURCE_DATE_EPOCH=1612137600
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.rmQLpO
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf pigz-2.5
+ /usr/bin/gzip -dc /builddir/build/SOURCES/pigz-2.5.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd pigz-2.5
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.qNOowF
+ umask 022
+ cd /builddir/build/BUILD
+ cd pigz-2.5
+ /usr/bin/make -O -j12 V=1 VERBOSE=1 'CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection   -c -o yarn.o yarn.c
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c zopfli/src/zopfli/lz77.c
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c zopfli/src/zopfli/katajainen.c
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c zopfli/src/zopfli/deflate.c
zopfli/src/zopfli/deflate.c: In function 'OptimizeHuffmanForRle':
zopfli/src/zopfli/deflate.c:452:24: warning: argument 1 range [18446744065119617024, 18446744073709551612] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
  452 |   good_for_rle = (int*)malloc(length * sizeof(int));
      |                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from zopfli/src/zopfli/lz77.h:28,
                 from zopfli/src/zopfli/deflate.h:28,
                 from zopfli/src/zopfli/deflate.c:20:
/usr/include/stdlib.h:539:14: note: in a call to allocation function 'malloc' declared here
  539 | extern void *malloc (size_t __size) __THROW __attribute_malloc__
      |              ^~~~~~
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection   -c -o try.o try.c
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c zopfli/src/zopfli/util.c
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c zopfli/src/zopfli/hash.c
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c zopfli/src/zopfli/cache.c
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c zopfli/src/zopfli/blocksplitter.c
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c zopfli/src/zopfli/symbols.c
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c zopfli/src/zopfli/tree.c
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -c zopfli/src/zopfli/squeeze.c
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection   -c -o pigz.o pigz.c
In file included from /usr/include/string.h:519,
                 from pigz.c:345:
In function 'strncpy',
    inlined from 'show_info' at pigz.c:3079:9:
/usr/include/bits/string_fortified.h:95:10: warning: '__strncpy_chk' specified bound depends on the length of the source argument [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
pigz.c: In function 'show_info':
pigz.c:3078:13: note: length computed here
 3078 |         n = strlen(g.inf) - compressed_suffix(g.inf);
      |             ^~~~~~~~~~~~~
gcc  -o pigz pigz.o yarn.o try.o deflate.o blocksplitter.o tree.o lz77.o cache.o hash.o util.o squeeze.o katajainen.o symbols.o -lm -lpthread -lz
ln -f pigz unpigz
In function 'strncpy',
    inlined from 'show_info' at pigz.c:3079:9:
/usr/include/bits/string_fortified.h:95:10: warning: '__builtin___strncpy_chk' specified bound depends on the length of the source argument [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^
pigz.c: In function 'show_info':
pigz.c:3078:13: note: length computed here
 3078 |         n = strlen(g.inf) - compressed_suffix(g.inf);
      |             ^
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%install): /bin/sh -e /var/tmp/rpm-tmp.geXAni
+ umask 022
+ cd /builddir/build/BUILD
+ '[' /builddir/build/BUILDROOT/pigz-2.5-1.fc34.x86_64 '!=' / ']'
+ rm -rf /builddir/build/BUILDROOT/pigz-2.5-1.fc34.x86_64
++ dirname /builddir/build/BUILDROOT/pigz-2.5-1.fc34.x86_64
+ mkdir -p /builddir/build/BUILDROOT
+ mkdir /builddir/build/BUILDROOT/pigz-2.5-1.fc34.x86_64
+ cd pigz-2.5
+ install -p -D pigz /builddir/build/BUILDROOT/pigz-2.5-1.fc34.x86_64/usr/bin/pigz
+ pushd /builddir/build/BUILDROOT/pigz-2.5-1.fc34.x86_64/usr/bin
~/build/BUILDROOT/pigz-2.5-1.fc34.x86_64/usr/bin ~/build/BUILD/pigz-2.5
+ ln pigz unpigz
+ popd
~/build/BUILD/pigz-2.5
+ install -p -D pigz.1 -m 0644 /builddir/build/BUILDROOT/pigz-2.5-1.fc34.x86_64/usr/share/man/man1/pigz.1
+ /usr/lib/rpm/find-debuginfo.sh -j12 --strict-build-id -m -i --build-id-seed 2.5-1.fc34 --unique-debug-suffix -2.5-1.fc34.x86_64 --unique-debug-src-base pigz-2.5-1.fc34.x86_64 --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 -S debugsourcefiles.list /builddir/build/BUILD/pigz-2.5
explicitly decompress any DWARF compressed ELF sections in /builddir/build/BUILDROOT/pigz-2.5-1.fc34.x86_64/usr/bin/pigz
extracting debug info from /builddir/build/BUILDROOT/pigz-2.5-1.fc34.x86_64/usr/bin/pigz
hard linked /builddir/build/BUILDROOT/pigz-2.5-1.fc34.x86_64/usr/lib/debug/usr/bin/pigz-2.5-1.fc34.x86_64.debug to /builddir/build/BUILDROOT/pigz-2.5-1.fc34.x86_64/usr/lib/debug/usr/bin/unpigz-2.5-1.fc34.x86_64.debug
dwz: Too few files for multifile optimization
original debug info size: 376kB, size after compression: 356kB
/usr/lib/rpm/sepdebugcrcfix: Updated 1 CRC32s, 0 CRC32s did match.
698 blocks
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/redhat/brp-ldconfig
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/redhat/brp-strip-lto /usr/bin/strip
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/redhat/brp-python-bytecompile '' 1 0
+ /usr/lib/rpm/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
Executing(%check): /bin/sh -e /var/tmp/rpm-tmp.uoVOfK
+ umask 022
+ cd /builddir/build/BUILD
+ cd pigz-2.5
+ make tests 'CFLAGS=-O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection'
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DNOZOPFLI -c -o pigzj.o pigz.c
In file included from /usr/include/string.h:519,
                 from pigz.c:345:
In function 'strncpy',
    inlined from 'show_info' at pigz.c:3079:9:
/usr/include/bits/string_fortified.h:95:10: warning: '__strncpy_chk' specified bound depends on the length of the source argument [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
pigz.c: In function 'show_info':
pigz.c:3078:13: note: length computed here
 3078 |         n = strlen(g.inf) - compressed_suffix(g.inf);
      |             ^~~~~~~~~~~~~
gcc  -o pigzj pigzj.o yarn.o try.o -lm -lpthread -lz
In function 'strncpy',
    inlined from 'show_info' at pigz.c:3079:9:
/usr/include/bits/string_fortified.h:95:10: warning: '__builtin___strncpy_chk' specified bound depends on the length of the source argument [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^
pigz.c: In function 'show_info':
pigz.c:3078:13: note: length computed here
 3078 |         n = strlen(g.inf) - compressed_suffix(g.inf);
      |             ^
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DPIGZ_DEBUG -g -c -o pigzt.o pigz.c
In file included from /usr/include/string.h:519,
                 from pigz.c:345:
In function 'strncpy',
    inlined from 'show_info' at pigz.c:3079:9:
/usr/include/bits/string_fortified.h:95:10: warning: '__strncpy_chk' specified bound depends on the length of the source argument [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
pigz.c: In function 'show_info':
pigz.c:3078:13: note: length computed here
 3078 |         n = strlen(g.inf) - compressed_suffix(g.inf);
      |             ^~~~~~~~~~~~~
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DPIGZ_DEBUG -g -c -o yarnt.o yarn.c
gcc  -o pigzt pigzt.o yarnt.o try.o deflate.o blocksplitter.o tree.o lz77.o cache.o hash.o util.o squeeze.o katajainen.o symbols.o -lm -lpthread -lz
In function 'strncpy',
    inlined from 'show_info' at pigz.c:3079:9:
/usr/include/bits/string_fortified.h:95:10: warning: '__builtin___strncpy_chk' specified bound depends on the length of the source argument [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^
pigz.c: In function 'show_info':
pigz.c:3078:13: note: length computed here
 3078 |         n = strlen(g.inf) - compressed_suffix(g.inf);
      |             ^
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DPIGZ_DEBUG -DNOTHREAD -g -c -o pigzn.o pigz.c
pigz.c: In function 'defaults':
pigz.c:4295:15: warning: implicit declaration of function 'x2nmodp' [-Wimplicit-function-declaration]
 4295 |     g.shift = x2nmodp(g.block, 3);
      |               ^~~~~~~
In file included from /usr/include/string.h:519,
                 from pigz.c:345:
In function 'strncpy',
    inlined from 'show_info' at pigz.c:3079:9:
/usr/include/bits/string_fortified.h:95:10: warning: '__strncpy_chk' specified bound depends on the length of the source argument [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   96 |                                   __glibc_objsize (__dest));
      |                                   ~~~~~~~~~~~~~~~~~~~~~~~~~
pigz.c: In function 'show_info':
pigz.c:3078:13: note: length computed here
 3078 |         n = strlen(g.inf) - compressed_suffix(g.inf);
      |             ^~~~~~~~~~~~~
gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -DPIGZ_DEBUG -DNOTHREAD -g -c -o tryn.o try.c
gcc  -o pigzn pigzn.o tryn.o deflate.o blocksplitter.o tree.o lz77.o cache.o hash.o util.o squeeze.o katajainen.o symbols.o -lm -lpthread -lz
In function 'strncpy',
    inlined from 'show_info' at pigz.c:3079:9:
/usr/include/bits/string_fortified.h:95:10: warning: '__builtin___strncpy_chk' specified bound depends on the length of the source argument [-Wstringop-overflow=]
   95 |   return __builtin___strncpy_chk (__dest, __src, __len,
      |          ^
pigz.c: In function 'show_info':
pigz.c:3078:13: note: length computed here
 3078 |         n = strlen(g.inf) - compressed_suffix(g.inf);
      |             ^
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid abstract instance DIE ref
/tmp/ccbDyyND.ltrans0.ltrans.o: in function `option':
<artificial>:(.text+0x2ab9): undefined reference to `x2nmodp'
/usr/bin/ld: /tmp/ccbDyyND.ltrans0.ltrans.o: in function `main':
<artificial>:(.text.startup+0x299): undefined reference to `x2nmodp'
collect2: error: ld returned 1 exit status
make: *** [Makefile:72: pigzn] Error 1

RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.uoVOfK (%check)
    Bad exit status from /var/tmp/rpm-tmp.uoVOfK (%check)
Finish: rpmbuild pigz-2.5-1.fc34.src.rpm
Finish: build phase for pigz-2.5-1.fc34.src.rpm
ERROR: Exception(/home/filiperosset/rpmbuild/my/pigz/pigz-2.5-1.fc34.src.rpm) Config(fedora-rawhide-x86_64) 0 minutes 30 seconds
INFO: Results and/or logs in: /home/filiperosset/rpmbuild/my/pigz/results_pigz/2.5/1.fc34
INFO: Cleaning up build root ('cleanup_on_failure=True')
Start: clean chroot
INFO: unmounting tmpfs.
Finish: clean chroot
ERROR: Command failed:
 # /usr/bin/systemd-nspawn -q -M 37cffca772c44ebc9bf3a61eae254717 -D /var/lib/mock/fedora-rawhide-x86_64/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.p76njxi3:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin --setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007" --setenv=PS1=<mock-chroot> \s-\v\$  --setenv=LANG=C.UTF-8 --setenv=CCACHE_DIR=/var/tmp/ccache --setenv=CCACHE_UMASK=002 --setenv=CCACHE_COMPRESS=True --resolv-conf=off bash --login -c /usr/bin/rpmbuild -bb --target x86_64 --nodeps /builddir/build/SPECS/pigz.spec

Could not execute mockbuild: Failed to execute command.
[filiperosset@raw pigz]$

**Comment by madler** [comment]
The x2nmodp link error is fixed with https://github.com/madler/pigz/commit/f310c0868634a1dbacdcdcb2dbce9501a8a87868 . The bogus warnings should be skirted by https://github.com/madler/pigz/commit/c9de6c53dcf3eb1071c7999c8accc43ef2b3f458 . Please give them a try.

Also it's usually a good idea to check the develop branch before reporting an issue.

**Comment by rosset** [comment]
thanks, both patches are working fine.
