### ISSUE TITLE
pigz return 1 when skips .gz

### ISSUE THREAD

**Issue by mcgru** [madler/pigz#87]
When `pigz -r fodler` finds .gz-file, it tels that it skips it, but return 1 error code.
In my opinion, pigz should either return 0 when find .gz or tell something like "error: file .gz found"

**Comment by Code7R** [comment]
Indeed, this is a deviation from gzip's behavior. gzip skips such files quietly and ends with 0 return.

**Comment by madler** [comment]
This will be fixed in the next version.
