### ISSUE TITLE
pigz -f appends additional .gz to name

### ISSUE THREAD

**Issue by mcgru** [madler/pigz#88]
When in --force mode, pigz compresses and appends additional .gz to filename: `pigz -f file.gz`  makes file.gz.gz .
Even if user intentionally applied option - do not double-compress file if gz-fingerprint found in it.
Is there any ephemeral cases when it is necessary to compress file with gzip and then compress compressed archive with gzip again? I think that probability for this intention is 1.0E-50, i.e. zero.
So, please, make some gloss on pigz: for the case if filename ends with .gz, let it look for the gzip-fingerprint in the file, and if it is really .gz (not just text with .gz-extention) - just do nothing (skip). If it is non-gzip file - pigz it, but do not append more .gz to filename.
In case if there is no --force option and .gz file encountered - just skip it without error (i've already made distinct issue on it).

**Comment by tomek-szczesny** [comment]
I think the point of "--force" parameter is to do exactly what the user demands, no questions asked.

**Comment by mcgru** [comment]
What for will anybody need such a behavior?
I admit that somehow non-gzipped file could have an extension .gz - in that case current --force behavior does what user wish - just compress what user gave in command line. But even in this case it's a term for discussion whether it needs to keep .gz.gz as an extension.
Yes, most utilities are "dumb" - do what they have to do without looking into the sense. So current --force behavior does.
But i offer to slightly change "dumbness" of this useful (but not yet widely used as system software) utility - just to look into first bytes and decide if it is already gzipped and if yes - not to RE-compress it.

**Comment by tomek-szczesny** [comment]
I disagree that most utilities are "dumb". I'd rather call them "simple". More sophisticated features, such as assessing whether the operation makes sense or not, is the default behavior of pigz. For example, by default it won't let you compress files into the console.
--force is exactly what most utilities recognize as "don't try to outsmart the user" flag, and for the sake of consistent user experience (and meeting user expectations), it should stay the way it is.
I believe there are other solutions for what you're trying to achieve.

**Comment by madler** [comment]
Concur with tomek.
