### ISSUE TITLE
`pigz` as a `gzip` replacement for reproducible builds?

### ISSUE THREAD

**Issue by dongcarl** [madler/pigz#90]
Given that `pigz` takes advantage of multiple processors/cores, I'm wondering if it is deterministic. We have been using `gzip -9n` for reproducible builds and it works, but it ends up taking quite a while, so I'm wondering if `pigz` would be a good replacement that can maintain determinism.

**Comment by madler** [comment]
It won't produce the same thing as gzip -9, but it will produce the same thing itself, for a given version of pigz and a given version of zlib.

**Comment by dongcarl** [comment]
Oh okay, will `pigz` be reproducible with itself even when run with differing `--processes`?

**Comment by madler** [comment]
Yes.

Of course, you'd have to keep all of the compression-related options the same (level, blocksize, independent, etc.).

**Comment by tansy** [comment]
As long as you use same compression settings, number of processes doesn't matter. Just speeds things up.

```
$ A=Zajdel-Limes_inferior.txt
$ for p in 1 2 3 4; do pigz -p$p -c $A > $A.gz-p$p; done
$ md5sum *.gz*
5d9eb4874a213bde2a7254b0c08017f0  Zajdel-Limes_inferior.txt.gz-p1
5d9eb4874a213bde2a7254b0c08017f0  Zajdel-Limes_inferior.txt.gz-p2
5d9eb4874a213bde2a7254b0c08017f0  Zajdel-Limes_inferior.txt.gz-p3
5d9eb4874a213bde2a7254b0c08017f0  Zajdel-Limes_inferior.txt.gz-p4
```

**Comment by dongcarl** [comment]
Ah okay very cool! Thank you all for your patient answers :-)

**Comment by haampie** [comment]
Tarballs aren't reproducible it seems: https://github.com/madler/pigz/issues/104
