### ISSUE TITLE
unpigz -p does not utilize all the threads

### ISSUE THREAD

**Issue by akhst7** [madler/pigz#92]
Hi, 

I run `unpigz -p 72 index.gz`  under Ubuntu on AWS EC2 but did not see utilization of all the threads.  Any help on this ? 

Thanks. 

The AWS EC2 sys info;

```
temp neofetch
            .-/+oossssoo+/-.               ubuntu@ip-172-31-28-73
        `:+ssssssssssssssssss+:`           ----------------------
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.2 LTS x86_64
    .ossssssssssssssssssdMMMNysssso.       Host: c5.18xlarge
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.8.0-1038-aws
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 1 hour, 42 mins
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 1664 (dpkg), 5 (snap)
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: zsh 5.8
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Terminal: /dev/pts/1
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel Xeon Platinum 8124M (72) @ 2.163GHz
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   GPU: 00:03.0 Amazon.com, Inc. Device 1111
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Memory: 1025MiB / 140761MiB
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/
  +sssssssssdmydMMMMMMMMddddyssssssss+
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.
```
 ```
unpigz -V
pigz 2.4
```

**Comment by IL2P** [comment]
unpigz can only use 1 thread for extracting but can offload some overhead to other threads. It is still faster at extraction than other alternatives I have tried.

From man page:
Decompression can't be parallelized, at least not without specially prepared deflate streams for that purpose. As a result, pigz uses a single thread (the main thread) for decompression, but will create three other threads for reading, writing, and check calculation, which can speed up decompression under some circumstances. Parallel decompression can be turned off by specifying one process ( -dp 1 or -tp 1 ).

**Comment by akhst7** [comment]
@IL2P, Thanks for the comment.    I still wish there is a way to make extraction/decompression faster though.

**Comment by ZhenshengLee** [comment]
Hi, I am a new user of unpigz.

> unpigz can only use 1 thread for extracting but can offload some overhead to other threads. It is still faster at extraction than other alternatives I have tried.

What's the difference between `unpigz` and `pigz -d` ? Form the doc of pigz and this issue, they both use only 1 thread to decompress.
