### ISSUE TITLE
PigZ deletes archive without warning even when fails to uncompress

### ISSUE THREAD

**Issue by Steve132** [madler/pigz#93]
I recently encountered a really frustrating potentially dangerous issue.    Steps to reproduce:

   
    $ pigz -d archive.zip
    pigz: warning: archive.zip: entries after the first were ignored
    $ unzip archive.zip
    unzip:  cannot find or open archive.zip, archive.zip.zip or archive.zip.ZIP.

Essentially, pigz warns that it only got one file *but then deletes the entire archive anyway*!! 

This is unacceptable, particularly because the primary first time users of pigz (like me) are likely to be people who are working with very large archives and searching for a way to accelerate decompression of such huge archives.   Therefore the default behavior violates the principle of least surprise and without warning causes total data loss.

In my case I was lucky becuase my archive was backed up, but it cost me 3 hours to redownload it again.

Solution:  the default behavior of pigz should absolutely be to NOT delete the whole archive on failure.  Instead, whenever possible, failure should result in a no-op to the original data.  Yes, uncompressing only one 300kb file of a 30GB archive counts as a failure.

The warning that is in place doesn't count sufficiently as a warning, because it proceeds to delete the source data anyways and doesn't ask you if you want to proeed.

At the bare minimum, a warning should come up that says "It looks like this operation will fail, and delete the whole archive, is that what you want [Y/N]" which can be overriden with something like -Y or --force.  "

**Comment by madler** [comment]
What version are you using? This was fixed in pigz 2.5. The current version is 2.6.
