### ISSUE TITLE
Undefined reference to COMB with NOTHREADS

### ISSUE THREAD

**Issue by nmoinvaz** [madler/pigz#97]
We get this new error in our CI when `NOTHREADS` is defined with pigz 2.7 cb8a432c91a1dbaee896cd1ad90be62e5d82d452:
```
[ 95%] Building C object CMakeFiles/pigz.dir/_deps/pigz-src/pigz.c.o
/home/runner/work/zlib-ng/zlib-ng/test/pigz/_deps/pigz-src/pigz.c:3598:20: warning: implicit declaration of function 'COMB' is invalid in C99 [-Wimplicit-function-declaration]
[ 97%] Building C object CMakeFiles/pigz.dir/_deps/pigz-src/try.c.o
[100%] Linking C executable pigz
/usr/bin/ld: CMakeFiles/pigz.dir/_deps/pigz-src/pigz.c.o: in function `infchk':
pigz.c:(.text+0xdbcb): undefined reference to `COMB'
```
https://github.com/zlib-ng/zlib-ng/runs/4828890476?check_suite_focus=true
Clang 11.0.0, Ubuntu 20

**Comment by madler** [comment]
Whoops. Thanks for testing NOTHREAD. Fixed in this commit: https://github.com/madler/pigz/commit/67fd6e436f4f479aead529a719e24d6864cf1dfa
