### ISSUE TITLE
Thread limiter doesnt seem to work on RHEL 7.9

### ISSUE THREAD

**Issue by mattcamp47** [madler/pigz#98]
I am working on a project where I will have multiple processes calling pigz on the same server.   The server is hosted in Azure and has 32 processors of type Standard D32ds v4 (32 vcpus, 128 GiB memory), which the processor type translates to 2.3 GHz Intel® XEON ® E5-2673 v4 (Broadwell) processor.

When I run it to convert to zip format without the parallel processor flag I get a 100gb file compressed to 10gb in a little over a minute.  When I run the same with the -p flag it seems to take as long as a regular zip file (sometimes doesn't even attempt to create the file)

I have tried the precompiled rpm with 2.4 and this most recent 2.7 version where I compiled locally with make and I see no apparent difference.   Is the -p flag in development, is RHEL not capable of taking advantage or am I doing something stupid and missing the obvious (Most likely the case).

This is the script I am running (for your consideration)
#!/bin/bash
file_name=$2
#set -x
cd $1
file_zip="${file_name}.zip"
[ -f "$file_zip" ] && rm -f $file_zip
echo "Compressing files in ${1}"
if [ -z "$3" ]
  then
    echo "No process thread limiter - using all CPU's"
    pigz -K -k -v $file_name
  else
    echo "Process thread limiter set - limiting compression threads to ${3}"
    pigz -K -k -v -p $3 $filename
fi

Thanks in advance for the consideration of this issue, look forward to working towards a resolution.

With Esteem,
Matthew Camp
Principal Cloud Automation Engineer
Health Care Service Corporation

**Comment by madler** [comment]
No, '-p' works. I'm not seeing a problem in my testing:

```
% time pigz -K -k -v linux-3.1.6.tar
linux-3.1.6.tar to linux-3.1.6.tar.zip 
pigz -K -k -v linux-3.1.6.tar  13.05s user 0.23s system 796% cpu 1.666 total

% time pigz -K -k -v -p 2 linux-3.1.6.tar
linux-3.1.6.tar to linux-3.1.6.tar.zip 
pigz -K -k -v -p 2 linux-3.1.6.tar  11.29s user 0.24s system 203% cpu 5.668 total

% time pigz -K -k -v -p 4 linux-3.1.6.tar
linux-3.1.6.tar to linux-3.1.6.tar.zip 
pigz -K -k -v -p 4 linux-3.1.6.tar  11.58s user 0.23s system 404% cpu 2.919 total
```

My system defaults to `-p 8`, and I am seeing about 800% cpu in that case. When I request `-p 2`, I get 200%, and with `-p 4`, I get 400%. All as expected.

**Comment by mattcamp47** [comment]
I think the problem I am experiencing is that I am running the above script from powershell (part of a much bigger process) and when powershell attempts to launch pigz from within its own thread it may not know how to determine the thread limiter.  I have also observed (within the above method) that if the file already exists, compression time takes much more time than if the file does not exist.  I will continue to do some more testing, but thanks for the quick reply and for providing such a superior product!

**Comment by madler** [comment]
No update on this, so closing.
